spring:
  datasource:
    url: jdbc:mysql://localhost:3306/naver_reservation?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: connectuser
    password: connect123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

#상품 이미지, 전시 상품 이미지, 맵 이미지 경로
property:
  image:
    url: /Applications/부스트코스/풀스택/reservation.v1.5/
